language: php

php:
    - 5.3
    - 5.4
    - 5.5

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - composer self-update

script:
    - composer update
    - vendor/bin/phpcs --standard=PSR2 src/
