language: php

sudo: false

cache:
    directories:
    - vendor
    - $HOME/.composer/cache

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- nightly
- hhvm

addons:
    apt:
        packages:
        - util-linux

matrix:
    fast_finish: true
    allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

notifications:
    email: false
    irc: "irc.iiens.net#Clicky"

before_script:
- pecl install pecl_http < /dev/null
- phpenv config-add tests/php.ini
- composer self-update -n
- composer install --dev -n
- /usr/bin/ssh -V || (echo "SSH not found" && exit 1)

script:
- vendor/bin/phpunit --coverage-clover clover.xml

after_script:
- composer require --dev "satooshi/php-coveralls dev-master"
- php vendor/bin/coveralls -n -v

