language: php

sudo: false

cache:
    directories:
    - vendor
    - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

addons:
    apt:
        packages:
        - util-linux

matrix:
    fast_finish: true
    allow_failures:
    - php: nightly
    - php: hhvm

notifications:
    email: false
    irc: "irc.iiens.net#Clicky"

before_script:
    - php -r 'exit(1 - version_compare(PHP_VERSION, "7", "<"));' && export RAPHF_VER=-1.1.2 PROPRO_VER=-1.0.2 HTTP_VER=-2.5.6 || true
    - pecl install raphf$RAPHF_VER < /dev/null
    - pecl install propro$PROPRO_VER < /dev/null
    - pecl install pecl_http$HTTP_VER < /dev/null
    - phpenv config-add tests/php.ini
    - rm -rf vendor/
    - rm composer.lock
    - composer self-update -n
    - composer install -n
    - /usr/bin/ssh -V || (echo "SSH not found" && exit 1)

script:
    - vendor/bin/phpunit --coverage-clover clover.xml

after_success:
    - composer require --dev satooshi/php-coveralls
    - travis_retry vendor/bin/coveralls -n -v
